services:
  - type: web
    name: youtube-transcript-q-a
    runtime: python
    plan: free              # Or 'starter' or 'standard' as needed
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: OPENAI_API_KEY
        sync: false         # Set the value securely in the Render Dashboard or as a secret
      - key: SCRAPERAPI_KEY
        sync: false
    # Optionally, set your python version (if needed):
    # - key: PYTHON_VERSION
    #   value: 3.10.12
